import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

const torusPro = localFont({
  src: [
    {
      path: "../public/fonts/Fontspring-DEMO-toruspro-thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/Fontspring-DEMO-toruspro-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Fontspring-DEMO-toruspro-semibold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-torus-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        cz-shortcut-listen="true"
        className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} ${torusPro.variable} antialiased`}
      >
        <div className="">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
